# ==============================
# Hugo Configuration for Lizhi Guo
# ==============================

title: Lizhi Guo(郭立志) # Website name
baseURL: 'https://example.com/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5
    -p ath: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep

############################
## NETLIFY CMS CONFIG
############################

params:
  netlify_cms:
    # 指定 CMS 后台路径
    admin_path: "admin"
    # 启用 Git Gateway
    git_gateway:
      enabled: true
      branch: main   # 修改为你仓库默认分支
    media_folder: "static/uploads"
    public_folder: "/uploads"

# Optional: Collections can be customized via `static/admin/config.yml`:
# Example for CMS content:
# collections:
#   - name: "blog"
#     label: "Blog Posts"
#     folder: "content/blog"
#     create: true
#     slug: "{{slug}}"
#     fields:
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       - { label: "Body", name: "body", widget: "markdown" }
#       - { label: "Tags", name: "tags", widget: "list" }
footer:
  copyright:
    notice: '© {year} Lizhi Guo(郭立志). All rights reserved.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
